apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.7.2
    helm:
      valuesObject:
        defaultSettings:
          # Storage configuration
          defaultReplicaCount: 2
          replicaAutoBalance: "best-effort"
          
          # S3 Backup configuration
          backupTarget: "s3://mxluk-k3s@weur"
          backupTargetCredentialSecret: "longhorn-s3-secret"
          
          # Encryption
          defaultDataLocality: "best-effort"
          
        # Enable CSI snapshots
        csi:
          attacherReplicaCount: 2
          provisionerReplicaCount: 2
          resizerReplicaCount: 2
          snapshotterReplicaCount: 2
        
        # Set as default storage class
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
        
        # Longhorn UI ingress (optional, accessible via Argo CD tunnel for now)
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true