# Daily backup job - keeps 3 daily backups
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"  # 2 AM daily
  task: "backup"
  groups:
    - default
  retain: 3
  concurrency: 2
  labels:
    schedule: daily
---
# Weekly backup job - keeps 8 weekly backups
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: "0 3 * * 0"  # 3 AM every Sunday
  task: "backup"
  groups:
    - default
  retain: 8
  concurrency: 1
  labels:
    schedule: weekly
---
# Snapshot job for quick recovery
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  cron: "0 * * * *"  # Every hour
  task: "snapshot"
  groups:
    - default
  retain: 24
  concurrency: 2
  labels:
    schedule: hourly