# File: apps/nextcloud/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm
    chart: nextcloud
    targetRevision: 8.4.1
    helm:
      valuesObject:
        # Use Apache variant - simpler and more stable
        image:
          flavor: apache
          
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "10G"
            nginx.ingress.kubernetes.io/proxy-buffering: "off"
            nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          hosts:
            - nextcloud.mxluk.de
          tls: []
        
        nextcloud:
          host: nextcloud.mxluk.de
          username: admin
          password: changeme123!
          
          # Database config
          existingSecret:
            enabled: false
          
          # PHP settings for better performance
          phpConfigs:
            uploadLimit.ini: |
              upload_max_filesize = 16G
              post_max_size = 16G
              max_input_time = 3600
              max_execution_time = 3600
              memory_limit = 512M
          
          configs:
            proxy.config.php: |-
              <?php
              $CONFIG = array (
                'trusted_proxies' => array(
                  0 => '10.42.0.0/16',
                  1 => '10.0.0.0/16',
                ),
                'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
                'overwriteprotocol' => 'https',
              );
        
        # Increase startup times for initial setup
        startupProbe:
          enabled: true
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        
        livenessProbe:
          enabled: true
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          enabled: true
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        # Use Longhorn for persistent storage
        persistence:
          enabled: true
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 10Gi
        
        # PostgreSQL database
        postgresql:
          enabled: true
          image:
            tag: latest
          auth:
            username: nextcloud
            password: nextcloud123!
            database: nextcloud
          primary:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 5Gi
        
        # Redis for caching  
        redis:
          enabled: true
          image:
            tag: latest
          auth:
            enabled: true
            password: redis123!
          master:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 1Gi
          replica:
            replicaCount: 0
        
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 2Gi
        
        # Cronjobs for Nextcloud maintenance
        cronjob:
          enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true