# File: apps/nextcloud/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm
    chart: nextcloud
    targetRevision: 6.2.2
    helm:
      valuesObject:
        image:
          flavor: fpm-alpine
        
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "10G"
            nginx.ingress.kubernetes.io/server-snippet: |-
              server_tokens off;
              proxy_hide_header X-Powered-By;
              rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
              rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
              rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
              rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
              location = /.well-known/carddav {
                return 301 $scheme://$host/remote.php/dav;
              }
              location = /.well-known/caldav {
                return 301 $scheme://$host/remote.php/dav;
              }
              location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
              }
              location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
                deny all;
              }
              location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
                deny all;
              }
          hosts:
            - nextcloud.mxluk.de
          tls: []
        
        nextcloud:
          host: nextcloud.mxluk.de
          username: admin
          password: changeme  # TODO: Change this!
          
          configs:
            proxy.config.php: |-
              <?php
              $CONFIG = array (
                'trusted_proxies' => array(
                  0 => '10.42.0.0/16',
                  1 => '10.0.0.0/16',
                ),
                'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
              );
        
        # Use Longhorn for persistent storage
        persistence:
          enabled: true
          storageClass: longhorn
          accessMode: ReadWriteOnce
          size: 10Gi
        
        # PostgreSQL database
        postgresql:
          enabled: true
          auth:
            username: nextcloud
            password: changeme  # TODO: Change this!
            database: nextcloud
          primary:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 5Gi
        
        # Redis for caching
        redis:
          enabled: true
          auth:
            enabled: true
            password: changeme  # TODO: Change this!
          master:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 1Gi
        
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi
        
        # Cronjobs for Nextcloud maintenance
        cronjob:
          enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true