apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mxluk/k3s-gitops
    targetRevision: HEAD
    path: apps/longhorn-config
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true