# Daily backup job - keeps 3 daily backups
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  name: backup-daily
  cron: "0 2 * * *"
  task: backup
  groups:
    - default
  retain: 3
  concurrency: 2
  labels:
    interval: daily
---
# Weekly backup job - keeps 8 weekly backups
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  name: backup-weekly
  cron: "0 3 * * 0"
  task: backup
  groups:
    - default
  retain: 8
  concurrency: 1
  labels:
    interval: weekly
---
# Snapshot job for quick recovery
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  name: snapshot-hourly
  cron: "0 * * * *"
  task: snapshot
  groups:
    - default
  retain: 24
  concurrency: 2
  labels:
    interval: hourly